webform.settings.third_party.webform_counter:
  type: config_object
  label: 'Webform Counter settings'
  mapping:
    offline_submissions_count:
      type: integer
      label: 'Offline submissions count'
    target_submissions_count:
      type: integer
      label: 'Target submissions count'
    submissions_count_text:
      type: plural_label
      label: 'Submissions Count Text'
