commerce_product.commerce_product_variation_type.*.third_party.commerce_ticketing:
  type: mapping
  label: 'Commerce ticketing third party settings'
  mapping:
    auto_create_ticket:
      type: boolean
      label: 'Auto create ticket'
    auto_activate_ticket:
      type: boolean
      label: 'Auto activate ticket'
    order_state:
      type: string
      label: 'Create the ticket when the order is in the following state'

commerce_order.commerce_order_type.*.third_party.commerce_ticketing:
  type: mapping
  label: 'Commerce ticketing third party settings'
  mapping:
    enable_ticketing:
      type: boolean
      label: 'Enable ticketing'
    ticket_type:
      type: string
      label: 'Type of the ticket'
    send_ticket_mail:
      type: boolean
      label: 'Queue an email to be sent with the ticket receipt'

field.formatter.settings.commerce_ticketing_qr_code:
  type: mapping
  label: 'QR Code image pseudofield display format settings'
  mapping:
    size:
      type: integer
      label: 'Size'
    margin:
      type: integer
      label: 'Margin'
    font_size:
      type: integer
      label: 'Font size'
    error_correction_level:
      type: string
      label: 'Error correction level'
    label_alignment:
      type: string
      label: 'Label alignment'
    background_color:
      type: string
      label: 'Background color'
    foreground_color:
      type: string
      label: 'Foreground color'
    label_text_color:
      type: string
      label: 'Label text color'

action.configuration.commerce_ticket_delete_action:
  type: action_configuration_default
  label: 'Delete Commerce Ticket'
