commerce_payment.commerce_payment_gateway.plugin.ccavenue_redirect:
  type: commerce_payment_gateway_configuration
  mapping:
    merchant_id:
      type: string
      label: 'Merchant id'
    access_code:
      type: string
      label: 'CCavenue access Code'
    working_key:
      type: string
      label: 'CCavenue Working key'
    currency:
      type: string
      label: 'Default Currency'
    language:
      type: string
      label: 'Language'
    pmode:
      type: string
      label: 'Mode'
