<?php

/**
 * @file
 * Commerce ticketing module hooks and alters.
 */

use Drupal\commerce\EntityHelper;
use Drupal\commerce_order\Entity\OrderItemType;
use Drupal\commerce_order\Entity\OrderType;
use Drupal\commerce_ticketing\Entity\CommerceTicketType;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\entity\BundleFieldDefinition;

/**
 * Implements hook_form_FORM_ID_alter() for 'commerce_order_type_form'.
 */
function commerce_ticketing_form_commerce_product_variation_type_form_alter(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\commerce_product\Entity\ProductVariationType $variation_type */
  $variation_type = $form_state->getFormObject()->getEntity();
  $options = [];

  if ($variation_type->id()) {
    /** @var \Drupal\commerce_order\Entity\OrderItemType $order_item_type */
    $order_item_type = OrderItemType::load($variation_type->getOrderItemTypeId());
    /** @var \Drupal\commerce_order\Entity\OrderType $order_type */
    $order_type = OrderType::load($order_item_type->getOrderTypeId());
    $workflow_manager = \Drupal::service('plugin.manager.workflow');
    $workflow_type = $workflow_manager->createInstance($order_type->getWorkflowId());
    $order_workflow_states = $workflow_type->getStates();
    foreach ($order_workflow_states as $key => $state) {
      $options[$key] = $state->getLabel();
    }

    $auto_create_ticket = $variation_type->getThirdPartySetting('commerce_ticketing', 'auto_create_ticket');
    $auto_activate_ticket = $variation_type->getThirdPartySetting('commerce_ticketing', 'auto_activate_ticket');
    $order_state = $variation_type->getThirdPartySetting('commerce_ticketing', 'order_state');
  }

  $form['commerce_ticketing'] = [
    '#type' => 'details',
    '#title' => t('Ticketing settings'),
    '#weight' => 1,
    '#open' => TRUE,
    '#description' => t('IMPORTANT: Please make sure that you enabled ticketing on the relevant order type.'),
    '#states' => [
      'visible' => [
        ':input[name="traits[purchasable_entity_ticket]"]' => ['checked' => TRUE],
      ],
    ],
  ];
  $form['commerce_ticketing']['auto_create_ticket'] = [
    '#type' => 'checkbox',
    '#title' => t('Automatically create a ticket for every order line item.'),
    '#default_value' => !empty($auto_create_ticket),
  ];

  if (!empty($options)) {
    $form['commerce_ticketing']['auto_activate_ticket'] = [
      '#type' => 'checkbox',
      '#title' => t('Automatically activate ticket for this variation type.'),
      '#default_value' => !empty($auto_activate_ticket),
    ];
    $form['commerce_ticketing']['order_state'] = [
      '#type' => 'select',
      '#title' => t('Activate ticket on order state'),
      '#options' => $options,
      '#default_value' => $order_state ?: 'completed',
      '#required' => TRUE,
      '#states' => [
        'visible' => [
          ':input[name="auto_activate_ticket"]' => ['checked' => TRUE],
        ],
      ],
    ];
  }

  $form['actions']['submit']['#submit'][] = 'commerce_ticketing_variation_type_form_submit';
}

/**
 * Submission handler for commerce_ticketing_form_commerce_product_variation_type_form_alter().
 */
function commerce_ticketing_variation_type_form_submit(array $form, FormStateInterface $form_state) {
  /** @var \Drupal\commerce_product\Entity\ProductVariationType $variation_type */
  $variation_type = $form_state->getFormObject()->getEntity();

  $auto_create_ticket = !empty($form_state->getValue('auto_create_ticket')) ? $form_state->getValue('auto_create_ticket') : FALSE;
  $auto_activate_ticket = !empty($form_state->getValue('auto_activate_ticket')) ? $form_state->getValue('auto_activate_ticket') : FALSE;
  $order_state = !empty($form_state->getValue('order_state')) ? $form_state->getValue('order_state') : '';

  $variation_type->setThirdPartySetting('commerce_ticketing', 'auto_create_ticket', $auto_create_ticket);
  $variation_type->setThirdPartySetting('commerce_ticketing', 'auto_activate_ticket', $auto_activate_ticket);
  $variation_type->setThirdPartySetting('commerce_ticketing', 'order_state', $order_state);
  $variation_type->save();
}

/**
 * Implements hook_form_FORM_ID_alter() for 'commerce_order_type_form'.
 */
function commerce_ticketing_form_commerce_order_type_form_alter(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\commerce_order\Entity\OrderTypeInterface $order_type */
  $order_type = $form_state->getFormObject()->getEntity();
  $enable_ticketing = $order_type->getThirdPartySetting('commerce_ticketing', 'enable_ticketing');
  $send_ticket_mail = $order_type->getThirdPartySetting('commerce_ticketing', 'send_ticket_mail');

  // Prepare a list of ticket types.
  $ticket_type_storage = \Drupal::entityTypeManager()->getStorage('commerce_ticket_type');
  $ticket_types = $ticket_type_storage->loadMultiple();
  $ticket_type = $order_type->getThirdPartySetting('commerce_ticketing', 'ticket_type');

  $form['commerce_ticketing'] = [
    '#type' => 'container',
    '#weight' => 4,
    '#element_validate' => ['commerce_ticketing_order_type_form_validate'],
  ];
  $form['commerce_ticketing']['enable_ticketing'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable tickets for this order type'),
    '#default_value' => !empty($enable_ticketing),
  ];
  $form['commerce_ticketing']['ticket_type'] = [
    '#type' => 'select',
    '#title' => t('Ticket type'),
    '#options' => EntityHelper::extractLabels($ticket_types),
    '#default_value' => $ticket_type ?: '',
    '#required' => TRUE,
    '#states' => [
      'visible' => [
        ':input[name="commerce_ticketing[enable_ticketing]"]' => ['checked' => TRUE],
      ],
    ],
  ];
  $form['commerce_ticketing']['send_ticket_mail'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable sending tickets via E-Mail automatically after checkout.'),
    '#default_value' => !empty($send_ticket_mail),
    '#states' => [
      'visible' => [
        ':input[name="commerce_ticketing[enable_ticketing]"]' => ['checked' => TRUE],
      ],
    ],
  ];
  $form['actions']['submit']['#submit'][] = 'commerce_ticketing_order_type_form_submit';
}

/**
 * Validation handler for commerce_shipping_form_commerce_order_type_form_alter().
 */
function commerce_ticketing_order_type_form_validate(array $element, FormStateInterface $form_state) {
  /** @var \Drupal\commerce_order\Entity\OrderTypeInterface $order_type */
  $order_type = $form_state->getFormObject()->getEntity();
  $previous_value = $order_type->getThirdPartySetting('commerce_ticketing', 'enable_ticketing');
  $settings = $form_state->getValue(['commerce_ticketing']);
  /** @var \Drupal\commerce\ConfigurableFieldManagerInterface $configurable_field_manager */
  $configurable_field_manager = \Drupal::service('commerce.configurable_field_manager');

  // Don't allow shipping to be disabled if there's data in the field.
  if ($previous_value && !$settings['enable_ticketing']) {
    $field_definition = commerce_ticketing_build_ticketing_field_definition($order_type->id());
    if ($configurable_field_manager->hasData($field_definition)) {
      $form_state->setError($element['enable_ticketing'], t('Ticketing cannot be disabled until all orders with ticketing data are deleted.'));
    }
  }
}

/**
 * Submission handler for commerce_shipping_form_commerce_order_type_form_alter().
 */
function commerce_ticketing_order_type_form_submit(array $form, FormStateInterface $form_state) {
  /** @var \Drupal\commerce_order\Entity\OrderTypeInterface $order_type */
  $order_type = $form_state->getFormObject()->getEntity();
  $previous_value = $order_type->getThirdPartySetting('commerce_ticketing', 'enable_ticketing');
  $settings = $form_state->getValue(['commerce_ticketing']);
  /** @var \Drupal\commerce\ConfigurableFieldManagerInterface $configurable_field_manager */
  $configurable_field_manager = \Drupal::service('commerce.configurable_field_manager');

  $field_definition = commerce_ticketing_build_ticketing_field_definition($order_type->id());
  if (!$previous_value && $settings['enable_ticketing']) {
    $configurable_field_manager->createField($field_definition);
  }
  elseif ($previous_value && !$settings['enable_ticketing']) {
    $configurable_field_manager->deleteField($field_definition);
  }

  $ticketing_enabled = $settings['enable_ticketing'] ? $settings['enable_ticketing'] : '';
  $ticket_type = $settings['ticket_type'] ? $settings['ticket_type'] : '';
  $send_ticket_mail = $settings['send_ticket_mail'] ? $settings['send_ticket_mail'] : '';

  $order_type->setThirdPartySetting('commerce_ticketing', 'enable_ticketing', $ticketing_enabled);
  $order_type->setThirdPartySetting('commerce_ticketing', 'ticket_type', $ticket_type);
  $order_type->setThirdPartySetting('commerce_ticketing', 'send_ticket_mail', $send_ticket_mail);
  $order_type->save();
}

/**
 * Builds the $order->tickets field definition.
 *
 * @param string $order_type_id
 *   The order type ID.
 *
 * @return \Drupal\entity\BundleFieldDefinition
 *   The field definition.
 */
function commerce_ticketing_build_ticketing_field_definition($order_type_id) {
  $field_definition = BundleFieldDefinition::create('entity_reference')
    ->setTargetEntityTypeId('commerce_order')
    ->setTargetBundle($order_type_id)
    ->setName('tickets')
    ->setLabel('Tickets')
    ->setCardinality(BundleFieldDefinition::CARDINALITY_UNLIMITED)
    ->setSetting('target_type', 'commerce_ticket')
    ->setSetting('handler', 'default');

  return $field_definition;
}

/**
 * Implements hook_entity_operation().
 */
function commerce_ticketing_entity_operation(EntityInterface $entity) {
  // Only show the "Tickets" operation link for commerce_order entities.
  if ($entity->getEntityTypeId() !== 'commerce_order') {
    return [];
  }
  // Do not show for a "cart" order.
  if ($entity->hasField('cart') && $entity->get('cart')->value) {
    return [];
  }
  // Only show if the user has the "administer commerce_ticketing" permission.
  if (!\Drupal::currentUser()->hasPermission('administer commerce_ticketing')) {
    return [];
  }
  $operations = [];
  $operations['tickets'] = [
    'title' => t('Tickets'),
    'url' => Url::fromRoute('entity.commerce_ticket.collection', [
      'commerce_order' => $entity->id(),
    ]),
    'weight' => 60,
  ];
  return $operations;
}

/**
 * Implements hook_entity_extra_field_info().
 */
function commerce_ticketing_entity_extra_field_info() {
  $extra = [];

  foreach (CommerceTicketType::loadMultiple() as $bundle) {
    $extra['commerce_ticket'][$bundle->Id()]['display']['date_purchase'] = [
      'label' => t('Date of purchase'),
      'weight' => 1,
    ];
    $extra['commerce_ticket'][$bundle->Id()]['display']['order_number'] = [
      'label' => t('Order number'),
      'weight' => 1,
    ];
    $extra['commerce_ticket'][$bundle->Id()]['display']['short_uuid'] = [
      'label' => t('Short UUID'),
      'weight' => 100,
    ];
  }

  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function commerce_ticketing_commerce_ticket_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  /** @var \Drupal\commerce_ticketing\CommerceTicketInterface $ticket */
  $ticket = $entity;
  $order = $ticket->getOrder();

  if ($display->getComponent('short_uuid')) {
    $build['short_uuid'] = [
      '#type' => 'markup',
      '#markup' => strtoupper(substr($ticket->uuid(), -7)),
    ];
  }
  if ($display->getComponent('date_purchase')) {
    $build['date_purchase'] = [
      '#type' => 'inline_template',
      '#template' => "<div><div class='{{ label_class }}'>{{ label }}</div><div class='{{ value_class }}'>{{ value }}</div></div>",
      '#context' => [
        'label_class' => 'field-item-date-purchase label',
        'label' => t('Date of purchase'),
        'value_class' => 'field-item-date-purchase item',
        'value' => \Drupal::service('date.formatter')->format($order->getCreatedTime(), 'html_date'),
      ],
    ];
  }
  if ($display->getComponent('order_number')) {
    $build['order_number'] = [
      '#type' => 'inline_template',
      '#template' => "<div><div class='{{ label_class }}'>{{ label }}</div><div class='{{ value_class }}'>{{ value }}</div></div>",
      '#context' => [
        'label_class' => 'field-item-order-number label',
        'label' => t('Order number'),
        'value_class' => 'field-item-order-number item',
        'value' => $order->getOrderNumber(),
      ],
    ];
  }
}

/**
 * Implements hook_mail().
 */
function commerce_ticketing_mail($key, &$message, $params) {
  switch ($key) {
    case 'ticket_receipt':
      if (isset($params['subject'])) {
        $message['subject'] = $params['subject'];
      }
      if (isset($params['body'])) {
        $message['body'][] = $params['body'];
      }
      if (isset($params['headers']) && is_array($params['headers'])) {
        $message['headers'] += $params['headers'];
      }
      if (isset($params['from'])) {
        $message['from'] = $params['from'];
      }
      if (isset($params['attachment'])) {
        $message['params']['attachments'][] = $params['attachment'];
      }
      $reply_to = $params['reply_to'] ?? '';
      if (empty($reply_to) && !empty($params['from'])) {
        $reply_to = $message['from'];
      }
      if ($reply_to) {
        $message['reply-to'] = $message['headers']['Reply-to'] = $reply_to;
      }
      break;
  }
}
