field.formatter.settings.boolean_single_state_formatter:
  type: mapping
  mapping:
    format:
      type: string
      label: 'Output format'
    format_custom_false:
      type: label
      label: 'Custom output for FALSE'
    format_custom_true:
      type: label
      label: 'Custom output for TRUE'
    format_inverse_state:
      type: boolean
      label: 'Inverse state'
